sudo: required
services:
  - docker
before_install:
  - docker build -t hasratsabit/docker-react -f Dockerfile.dev .
script:
  - docker run hasratsabit/docker-react npm run test -- --coverage --watchAll=false